### ISSUE TITLE
Updating built-in node property openhorizon.allowPrivileged cause anax panic

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1459]
Updating node built-in property openhorizon.allowPrivileged to an integer instead of  boolean caused anax panic.
hzn command should check the date type for this built-in property before commit the change.

````
$hzn policy patch '{"properties":[{"name": "openhorizon.allowPrivileged", "value": 5}]}'
Node policy updated.

$ hzn policy list
{
  "properties": [
    {
      "name": "purpose",
      "value": "aws-testing"
    },
    {
      "name": "openhorizon.hardwareId",
      "value": "d5c7a2dc97608a6020d7656c4dd885e69f38dbc0"
    },
    {
      "name": "openhorizon.cpu",
      "value": 4
    },
    {
      "name": "openhorizon.arch",
      "value": "amd64"
    },
    {
      "name": "openhorizon.memory",
      "value": 1998
    },
    {
      "name": "openhorizon.allowPrivileged",
      "value": 5
    }
  ],
  "constraints": [
    "iame2edev=true"
  ]
}
````
Then running other hzn command failed with error.
The anax log showed the following panic:
````
I0128 00:15:40.111530    9268 policy.go:93] Exchange RPC getting node policy for mycluster/Lings-MBP.fios-router.home.
I0128 00:15:40.412999    9268 builtin_properties.go:57] Found existing policy with {openhorizon.allowPrivileged 5 }
panic: interface conversion: interface {} is float64, not bool

goroutine 54 [running]:
github.com/open-horizon/anax/externalpolicy.CreateNodeBuiltInPolicy(0xc4205c0100, 0xc4208e22d0, 0x0, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/externalpolicy/builtin_properties.go:58 +0x1002
github.com/open-horizon/anax/exchangesync.GetProcessedExchangeNodePolicy(0xc420bcf880, 0xc42066eac0, 0xc42066eae0, 0xc4205ca3c0, 0x0, 0x0, 0xc4200a23f0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node_policy.go:95 +0x18a
github.com/open-horizon/anax/exchangesync.SyncNodePolicyWithExchange(0xc4205ca3c0, 0xc420bcf880, 0xc42066eac0, 0xc42066eae0, 0x0, 0x0, 0x0, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node_policy.go:28 +0x104
github.com/open-horizon/anax/exchangesync.NodePolicyInitalSetup(0xc4205ca3c0, 0xc4205bc900, 0xc42066eac0, 0xc42066eae0, 0x0, 0x0, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node_policy.go:264 +0x3b5
github.com/open-horizon/anax/agreement.(*AgreementWorker).syncOnInit(0xc420b3a0c0, 0xc420b2c3f0, 0xe4951a)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/agreement.go:478 +0x461
github.com/open-horizon/anax/agreement.(*AgreementWorker).Initialize(0xc420b3a0c0, 0xe4bc82)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/agreement.go:264 +0x414
github.com/open-horizon/anax/worker.(*BaseWorker).Start.func1(0xc420b3a0c0, 0xfad340, 0xc420b3a0c0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:318 +0x8a
created by github.com/open-horizon/anax/worker.(*BaseWorker).Start
	/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:312 +0x5c
Anax run number 608 ended with exit code 0.
Respawning anax...
```

**Comment by jiportilla** [comment]
--- The CLI command output is not correct, Dave is opening an issue to correct it

**Comment by jiportilla** [comment]
Error: bad HTTP code 500 from PATCH http://localhost:8510/node/policy: Unable to sync the local db with the exchange node policy. Property openhorizon.allowPrivileged must have a boolean value (true or false).
