### ISSUE TITLE
Agbot panics on HTTP 500 from exchange while making an agreement

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1475]
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot error E0130 05:04:31.189432       8 service.go:294] Exchange RPC Invocation of GET at http://edge-computing-exchange/v1/orgs/IBM/services?url=ibm.helloworld&version=1.0.0&arch=arm64 failed invoking HTTP request, status: 500, response: There was an internal server error.
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot error panic: runtime error: invalid memory address or nil pointer dereference
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb45053]
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot goroutine 2947 [running]:
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).InitiateNewAgreement(0xc420788f00, 0xfb1e20, 0xc420673380, 0xc42a160480, 0xc4209d1830, 0xc4206cade0, 0x24)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementworker.go: 380 +0x1803
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot github.com/open-horizon/anax/agreementbot.(*BasicAgreementWorker).start(0xc420beba80, 0xc4206aca20, 0xc4209d1830)
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot 	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_agreement_worker.go:118 +0x2d2c
Jan 30 00:04:31 edge-computing-agbot-76bfdfcb75-4nstk edge-computing-agbot created by github.com/open-horizon/anax/agreementbot.(*BasicProtocolHandler).Initialize
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_protocol_handler.go:69 +0x2f8

**Comment by dabooz** [comment]
Doug Verified that this no longer happens
