### ISSUE TITLE
Panic in anax agent code

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1695]
Scenario :
- Agent registers with a policy and gets an agreement
- hzn command is run to remove the node policy
- Saw a kernel panic in node_policy.go

I think exchangeNodePolicy needs to be checked for nil before accessing on line 97

Apr 29 13:44:48 edge-scale-test13 anax[4346]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 29 13:44:48 edge-scale-test13 anax[4346]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9cd46f]
Apr 29 13:44:48 edge-scale-test13 anax[4346]: goroutine 8 [running]:
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/exchangesync.GetProcessedExchangeNodePolicy(0xc0000f62d0, 0xc0002f8260, 0xc0002f82a0, 0xc0001be5a0, 0x946760, 0xc0007bb960, 0xc0007bb8e0)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node_policy.go:97 +0x16f
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/exchangesync.SyncNodePolicyWithExchange(0xc0001be5a0, 0xc0000f62d0, 0xc0002f8260, 0xc0002f82a0, 0x0, 0x0, 0x0, 0x0)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node_policy.go:28 +0xf0
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/agreement.(*AgreementWorker).checkNodePolicyChanges(0xc0000de000)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/node.go:242 +0x3c4
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/agreement.(*AgreementWorker).CommandHandler(0xc0000de000, 0x1d2b1a0, 0x2a1b178, 0x0)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/agreement.go:442 +0x397
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/worker.(*BaseWorker).internalCommandhandler(0xc0000de000, 0x1d81c20, 0xc0000de000, 0x1d2b1a0, 0x2a1b178, 0x0)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:307 +0x306
Apr 29 13:44:48 edge-scale-test13 anax[4346]: github.com/open-horizon/anax/worker.(*BaseWorker).Start.func1(0xc0000de000, 0x1d81c20, 0xc0000de000)
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:342 +0x5e9
Apr 29 13:44:48 edge-scale-test13 anax[4346]: created by github.com/open-horizon/anax/worker.(*BaseWorker).Start
Apr 29 13:44:48 edge-scale-test13 anax[4346]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:320 +0x5c
Apr 29 13:44:48 edge-scale-test13 systemd[1]: horizon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 29 13:44:48 edge-scale-test13 systemd[1]: horizon.service: Failed with result 'exit-code'.

**Comment by dlarson04** [comment]
closing... code now checks for nil
