### ISSUE TITLE
[BUG] Edge cluster agent pod becomes hung in a "terminating" state

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#1776]
Description: In different observed conditions the edge cluster pods can become stuck in a terminating state. This happens when kubernetes manages the deployment resource to deploy a new pod, it attempts to delete the old pod but hangs.

I have observed this to occur almost anytime a new pod is created from the deployment. I was able to replicate this with just a "kubectl pod delete" forcing a new resource to spawn and when updating the kubernetes deployment which causes a new pod to become created.

Version of Anax tested: 2.26.7, also noticed this in 2.26.5

Reproduction of issue:

```
root@mcgj-test-cluster41:~# kubectl get pods -n openhorizon-agent
NAME                     READY   STATUS    RESTARTS   AGE
agent-64b84f84b8-gjn29   1/1     Running   0          16h
root@mcgj-test-cluster41:~# kubectl delete pod -n openhorizon-agent agent-64b84f84b8-gjn29
pod "agent-64b84f84b8-gjn29" deleted

^C

root@mcgj-test-cluster41:~# kubectl get pods -n openhorizon-agent
NAME                     READY   STATUS        RESTARTS   AGE
agent-64b84f84b8-gjn29   1/1     Terminating   0          16h
agent-64b84f84b8-hlqdh   1/1     Running       0          88s

root@mcgj-test-cluster41:~# kubectl get pods -n openhorizon-agent
NAME                     READY   STATUS        RESTARTS   AGE
agent-64b84f84b8-gjn29   1/1     Terminating   0          16h
agent-64b84f84b8-hlqdh   1/1     Running       0          12m
```

**Comment by dabooz** [comment]
@omega2733 How do you know this is a horizon problem and not a base Kube problem? Do you have more info on what is happening in the agent container?

**Comment by omega2733** [comment]
This could be a kube problem, but based on the logs I don't believe so. When kube requests anax to terminate it tries to respawn continuously but ends up running into a panic due to timeout and never terminates. Here's some data from kubectl get logs, let me know what other data you need to debug if it's kube or anax and I'll be happy to grab it.

This is the same error we run into when trying to update the pod etc config, but in this scenario I didn't perform any of those just tried to delete the pod to get a new one spun up. I'm almost positive this happened from a clean installation as well (before I modified configs). However that makes me wonder if it's an artifact, I'll see if I can re-create it in a clean environment again. 

This also happened with one other env in another scenario which makes me believe it's not limited to this specific env.

```
goroutine 1 [running]:
main.main()
        /tmp/anax-gopath/src/github.com/open-horizon/anax/main.go:80 +0x1f16
Anax run number 517 ended with exit code 0.
Respawning anax...
/usr/horizon/bin/anax -v 3 -logtostderr -config /etc/horizon/anax.json
I0519 15:12:50.055059    3190 main.go:63] Using config: Edge: {ServiceStorage , APIListen 127.0.0.1:8510, DBPath /var/horizon/, DockerEndpoint , DockerCredFilePath , DefaultCPUSet , DefaultServiceRegistrationRAM: 0, StaticWebContent: /usr/horizon/web/, PublicKeyPath: /etc/horizon/trust/mtn-publicKey.pem, TrustSystemCACerts: true, CACertsPath: , ExchangeURL: https://icp-console.apps.rested-squid.purple-chesterfield.com/edge-exchange/v1/, DefaultHTTPClientTimeoutS: 30, PolicyPath: /etc/horizon/policy.d/, ExchangeHeartbeat: 60, AgreementTimeoutS: 600, DVPrefix: , RegistrationDelayS: 0, ExchangeMessageTTL: 1800, ExchangeMessageDynamicPoll: true, ExchangeMessagePollInterval: 10, ExchangeMessagePollMaxInterval: 120, ExchangeMessagePollIncrement: 10, UserPublicKeyPath: , ReportDeviceStatus: true, TrustCertUpdatesFromOrg: true, TrustDockerAuthFromOrg: true, ServiceUpgradeCheckIntervalS: 300, MultipleAnaxInstances: false, DefaultServiceRetryCount: 2, DefaultServiceRetryDuration: 600, NodeCheckIntervalS: 15, FileSyncService: {APIListen: agent-64b84f84b8-hlqdh, APIPort: 0, APIProtocol: https, PersistencePath: , AuthenticationPath: , CSSURL: https://icp-console.apps.rested-squid.purple-chesterfield.com/edge-css/, CSSSSLCert: , PollingRate: 0}, InitialPollingBuffer: {120}, BlockchainAccountId: , BlockchainDirectoryAddress }, AgreementBot: {TxLostDelayTolerationSeconds: 0, AgreementWorkers: 0, DBPath: , Postgresql: {Host: , Port: , User: , Password: ******, DBName: , SSLMode:  MaxOpenConnections: 0}, PartitionStale: 0, ProtocolTimeoutS: 0, AgreementTimeoutS: 0, NoDataIntervalS: 0, ActiveAgreementsURL: , ActiveAgreementsUser: , ActiveAgreementsPW: ******, PolicyPath: , NewContractIntervalS: 0, ProcessGovernanceIntervalS: 0, IgnoreContractWithAttribs: , ExchangeURL: https://icp-console.apps.rested-squid.purple-chesterfield.com/edge-exchange/v1/, ExchangeHeartbeat: 0, ExchangeId: , ExchangeToken: ******, DVPrefix: , ActiveDeviceTimeoutS: 0, ExchangeMessageTTL: 0, MessageKeyPath: , DefaultWorkloadPW: ******, APIListen: , SecureAPIListenHost: , SecureAPIListenPort: , SecureAPIServerCert: , SecureAPIServerkey: , PurgeArchivedAgreementHours: 0, CheckUpdatedPolicyS: 0, CSSURL: , CSSSSLCert: , AgreementBatchSize: 200}, Collaborators: {HTTPClientFactory: &{0x755990 0 10}, KeyFileNamesFetcher: &{0x756180}}, ArchSynonyms: {map[aarch64:arm64 armhf:arm x86_64:amd64]}
I0519 15:12:50.055181    3190 main.go:64] GOMAXPROCS: 2
panic: timeout
```

**Comment by varatep** [comment]
I'm able to reproduce this on @t-fine's cluster as well.

## Background info

The cluster seems to be stuck in a terminating state with no indicators in the logs.
We might be able to assume that this was a result of switching policies since his cluster matched with my policy and started an agreement and the corresponding pods. Then we created another policy that matched with the node, and very shortly after, deleted the original policy the node was matching on. It’s currently listing both agreements and the pods are stuck in a terminating state.

## Agreements

```
[agentuser@agent-797f9595d6-mbmsr ~]$ hzn agreement list
[
  {
    "name": "Policy for mycluster/tfine-cluster-apollo1 merged with mycluster/varatep-service_1.0.0_amd64-policy",
    "current_agreement_id": "dfc0b5c4655158cd54f6bb599b3f36105de884803a7d1529e4dec801fde1596e",
    "consumer_id": "IBM/mycluster-agbot",
    "agreement_creation_time": "2020-05-15 22:44:32 +0000 UTC",
    "agreement_accepted_time": "2020-05-15 22:44:42 +0000 UTC",
    "agreement_finalized_time": "2020-05-15 22:44:43 +0000 UTC",
    "agreement_execution_start_time": "2020-05-15 22:44:48 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "varatep-service",
      "org": "mycluster",
      "version": "1.0.0",
      "arch": "amd64"
    }
  },
  {
    "name": "Policy for mycluster/tfine-cluster-apollo1 merged with mycluster/troy.operator_0.0.1_amd64",
    "current_agreement_id": "60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776",
    "consumer_id": "IBM/mycluster-agbot",
    "agreement_creation_time": "2020-05-15 22:44:56 +0000 UTC",
    "agreement_accepted_time": "2020-05-15 22:45:05 +0000 UTC",
    "agreement_finalized_time": "2020-05-15 22:45:22 +0000 UTC",
    "agreement_execution_start_time": "2020-05-15 22:45:11 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "troy.operator",
      "org": "mycluster",
      "version": "0.0.1",
      "arch": "amd64"
    }
  }
]
```

## Pods

```
root@gormand1:~# kubectl get pods -n openhorizon-agent
NAME                                   READY   STATUS        RESTARTS   AGE
agent-797f9595d6-mbmsr                 1/1     Running       0          5d2h
topservice-765f58848-xtb5f             1/1     Terminating   0          5d1h
topservice-operator-7b6858f656-jm8pb   1/1     Terminating   0          5d1h
topservice-operator-944f55857-5k7t8    1/1     Running       1          2d21h
*Logs*
  "2020-05-15 22:44:56:   Node received Proposal message using agreement 60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776 for service mycluster/troy.operator from the agbot IBM/mycluster-agbot.",
  "2020-05-15 22:45:06:   Agreement reached for service troy.operator. The agreement id is 60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776.",
  "2020-05-15 22:45:06:   Start dependent services for mycluster/troy.operator.",
  "2020-05-15 22:45:06:   Start workload service for mycluster/troy.operator.",
  "2020-05-15 22:45:11:   Workload service containers for mycluster/troy.operator are up and running.",```

**Comment by linggao** [comment]
Works fine with in in microk8s.
````
# kubectl delete pod -n openhorizon-agent ${POD}
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                         READY   STATUS        RESTARTS   AGE
agent-8cdb5ddb7-7m7kx        1/1     Terminating   79         13h
agent-8cdb5ddb7-pdn9x        1/1     Running       0          25s
topservice-765f58848-q7whw   1/1     Terminating   31         164m
````
````
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                         READY   STATUS        RESTARTS   AGE
agent-8cdb5ddb7-pdn9x        1/1     Running       0          35s
topservice-765f58848-q7whw   1/1     Terminating   31         164m
````
````
 # microk8s.kubectl get pod  -n openhorizon-agent
NAME                    READY   STATUS    RESTARTS   AGE
agent-8cdb5ddb7-pdn9x   1/1     Running   0          48s
````

**Comment by t-fine** [comment]
For a little more information here, I had my cluster node `tfine-cluster-apollo1` registered with an operator of mine but when I ran `hzn unregister -fD` the pods remained in the terminating state 
```
root@gormand1:~# kubectl get pod -n openhorizon-agent
NAME                                          READY   STATUS        RESTARTS   AGE
agent-6d8b8895f-bpwm9                         1/1     Running       0          2d19h
example-ibmserviceoperator-7555bb584c-7t2xc   1/1     Terminating   0          6m22s
example-ibmserviceoperator-7555bb584c-dkczr   1/1     Terminating   0          6m22s
example-ibmserviceoperator-7555bb584c-zfctd   1/1     Terminating   0          6m22s
simple-operator-694c78f684-294kz              1/1     Terminating   0          13m
```

this is a microk8s cluster as well. I believe the issue here is that the `hzn unregister` command should fully delete the pods because I'm seeing an issue of the terminating operator retaining a "lock" on the ""Leader" role which does not let me subsequently running operators start their jobs, as you can see below

```
root@gormand1:~# kubectl logs simple-operator-694c78f684-294kz -n openhorizon-agent
{"level":"info","ts":1590081555.2479174,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1590081555.248013,"logger":"cmd","msg":"Go Version: go1.14.3"}
{"level":"info","ts":1590081555.2480578,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1590081555.2480826,"logger":"cmd","msg":"Version of operator-sdk: v0.17.1"}
{"level":"info","ts":1590081555.2484837,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1590081555.5459065,"logger":"leader","msg":"Found existing lock","LockOwner":"simple-operator-67876bdc95-2zw27"}
{"level":"info","ts":1590081555.55766,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081556.6904442,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081559.0776932,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081563.6256022,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081572.3416765,"logger":"leader","msg":"Not the leader. Waiting."}
```

**Comment by LiilyZhang** [comment]
Verified. hzn node list and hzn agreement list stays in the new pod  (after kubectl delete <old-pod-id>)
