### ISSUE TITLE
Panic in agbot results in CrashLoopBackoff

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1800]
I think this was in the scenario were the Exchange pods were not in a good state (possibly in CrashLoopBackoff) and the agbots ended up in CrashLoopBackoff too.  
From the agbot logs, I see 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x1575619]

goroutine 64 [running]:
github.com/open-horizon/anax/agreementbot.(*AgreementBotWorker).syncOnInit(0xc0000f6000, 0x3c, 0x1)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementbot.go:1172 +0x149
github.com/open-horizon/anax/agreementbot.(*AgreementBotWorker).stalePartitions(0xc0000f6000, 0xc00079c0e0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementbot.go:1612 +0x2b1
github.com/open-horizon/anax/worker.(*BaseWorker).DispatchSubworker.func1(0xc0000f6000, 0x1ae28b6, 0x1b, 0xc0001ba1c0, 0xc0001284b8, 0x190d300, 0xc000103540)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:467 +0x22a
created by github.com/open-horizon/anax/worker.(*BaseWorker).DispatchSubworker
        /tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:454 +0xc8
```

**Comment by dlarson04** [comment]
with version 2.26.10, I haven't seen this startup issue in the agbots with several agbot restarts
