### ISSUE TITLE
Panic in agbot on startup

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1809]
```
I0526 22:27:53.310513       8 worker.go:348] CommandDispatcher: AgBot command processor non-blocking for commands
I0526 22:27:53.310536       8 worker.go:296] CommandDispatcher: AgBot received command: ServedPolicyCommand
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x158bc6e]
goroutine 712 [running]:
github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).CancelAgreement(0xc000690230, 0x1e9f760, 0xc0002161e0, 0xc0000fd540, 0x40, 0xca, 0xc00013e450, 0x24, 0xc00062a020)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementworker.go:1027 +0x3ae
github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).HandleAgreementReply(0xc000690230, 0x1e9f760, 0xc0002161e0, 0xc0003fb980, 0xc00013e450, 0x24, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementworker.go:879 +0x2e1
github.com/open-horizon/anax/agreementbot.(*BasicAgreementWorker).start(0xc00062d9f0, 0xc000100960, 0xc00031fe00)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_agreement_worker.go:148 +0x3d9
created by github.com/open-horizon/anax/agreementbot.(*BasicProtocolHandler).Initialize
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_protocol_handler.go:70 +0x2a9
```

**Comment by dlarson04** [comment]
dave opened one already
