### ISSUE TITLE
An attempt to deploy an operator terminated abnormally if the operator's CRD manifest version is v1

### ISSUE THREAD

**Issue by takeyan** [open-horizon/anax#1937]
An attempt to deploy an operator (triggered by an agreement) terminated abnormally with a message in the eventlog:
"2020-07-29 12:42:56:   Start terminating agreement for mqttprovider-operator. Termination reason: service terminated“ 

```
"2020-07-29 12:42:45:   Node received Proposal message using agreement 12a60afdc451ce80756b7432fa8e630e6ce9c7a311149ae0caaf335598c79c3d for service ieamcluster/mqttprovider-operator from the agbot IBM/ieamcluster-agbot.",
"2020-07-29 12:42:56:   Agreement reached for service mqttprovider-operator. The agreement id is 12a60afdc451ce80756b7432fa8e630e6ce9c7a311149ae0caaf335598c79c3d.",
"2020-07-29 12:42:56:   Start workload service for ieamcluster/mqttprovider-operator.",
"2020-07-29 12:42:56:   Start terminating agreement for mqttprovider-operator. Termination reason: service terminated",
"2020-07-29 12:42:56:   Complete terminating agreement for mqttprovider-operator. Termination reason: service terminated",
"2020-07-29 12:42:57:   Workload destroyed for mqttprovider-operator"
```

We found that the open-horizon container agent can deploy operators successfully if the CRD manifest version is v1beta1. Operator SDK v0.18 or above generates CRD v1 meanwhile Operator SDK v0.17 generates v1beta1. It looks that the open-horizon container agent prerequisites Operator SDK v0.17 or below.

**Comment by linggao** [comment]
It happens in another case when user issued `hzn unregister -fDr`. The agent was panic with the following: 
````
I0810 17:12:03.799583   76141 kubeworker.go:155] Kubernetes Worker: begin uninstall of Kube Deployment b48b78505d29568693c7bb3e05f2f9e4b8da6e16d75c8c6f68b22aace7626a49
panic: interface conversion: interface {} is *v1beta1.Deployment, not *v1.Deployment
goroutine 126 [running]:
github.com/open-horizon/anax/kube_operator.getOperatorNamespace(0xc000827e00, 0x4, 0x4, 0xc000827e00, 0xc000525c20, 0x4)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/kube_operator/client.go:496 +0x551
github.com/open-horizon/anax/kube_operator.KubeClient.Uninstall(0xc0007c6840, 0xc000b35000, 0x758, 0xc0004f5cc0, 0x40, 0x0, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/kube_operator/client.go:246 +0xf3
github.com/open-horizon/anax/kube_operator.(*KubeWorker).uninstallKubeOperator(0xc0002942a0, 0xc0003bb660, 0xc0004f5cc0, 0x40, 0x0, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/kube_operator/kubeworker.go:160 +0x153
github.com/open-horizon/anax/kube_operator.(*KubeWorker).CommandHandler(0xc0002942a0, 0x1e272e0, 0xc00017c450, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/kube_operator/kubeworker.go:110 +0x123f
github.com/open-horizon/anax/worker.(*BaseWorker).internalCommandhandler(0xc0002942a0, 0x1e7fc40, 0xc0002942a0, 0x1e272e0, 0xc00017c450, 0x0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:307 +0x306
github.com/open-horizon/anax/worker.(*BaseWorker).Start.func1(0xc0002942a0, 0x1e7fc40, 0xc0002942a0)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:342 +0x5e9
created by github.com/open-horizon/anax/worker.(*BaseWorker).Start
	/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:320 +0x5c
Anax run number 2905 ended with exit code 0.
Respawning anax...
````

**Comment by MaxMcAdam** [comment]
Verified in local build
