### ISSUE TITLE
Make sure 'hzn reginput' returns new format for userinput and handles privileged setting in service

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1952]
And prompt the user to add a property for privileged if one of the services contains privileged in the deployment string.
````
{
  "properties": [
    {
      "name": "openhorizon.allowPrivileged",
      "value": true
    }
  ]
}
````
By new format, we mean the format that you get from `hzn userinput list`, like 
````
[
  {
    "serviceOrgid": "IBM",
    "serviceUrl": "https://bluehorizon.network/services/netspeed",
    "serviceArch": "amd64",
    "serviceVersionRange": "[2.2.0,INFINITY)",
    "inputs": [
      {
        "name": "var1",
        "value": "aString"
      },
      {
        "name": "var2",
        "value": 5
      },
      {
        "name": "var3",
        "value": 22.2
      }
    ]
  },
  {
    "serviceOrgid": "e2edev@somecomp.com",
    "serviceUrl": "https://bluehorizon.network/services/netspeed",
    "serviceArch": "amd64",
    "serviceVersionRange": "2.2.0",
    "inputs": [
      {
        "name": "var1",
        "value": "node_String"
      },
      {
        "name": "var2",
        "value": 20
      },
      {
        "name": "var3",
        "value": 23.2
      }
    ]
  },
  {
    "serviceOrgid": "IBM",
    "serviceUrl": "https://bluehorizon.network/service-cpu",
    "serviceArch": "amd64",
    "serviceVersionRange": "[0.0.0,INFINITY)",
    "inputs": [
      {
        "name": "cpu_var1",
        "value": "ibmnodevar1"
      }
    ]
  },
....
]
````

Please also skip the services that has the wrong type (device, cluster or both) with the node type (device or cluster). So there are 3 pieces for this issue:
- [ ] produce new userinput
- [ ] produce a sample node policy file if one of the services needs privileged mode.
- [ ] skip services that has the wrong type.

**Comment by linggao** [comment]
This command has not been visited for a long time. I ran it today and saw the following panic. 
````
hzn reginput -n an12345:abcdefg userdev e2edev@somecomp.com/sall -f /tmp/in.json
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/open-horizon/anax/semanticversion.singleVersion(0x0, 0x0, 0x17034b6)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/semanticversion/version.go:310 +0x112
github.com/open-horizon/anax/semanticversion.Version_Expression_Factory(0x0, 0x0, 0x600, 0x6a, 0xc00007e150)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/semanticversion/version.go:71 +0x1ef
github.com/open-horizon/anax/cli/register.isWithinRanges(0xc000219b98, 0x5, 0xc000048980, 0x1, 0x1, 0x4d)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/register/register.go:691 +0xa1
github.com/open-horizon/anax/cli/register.GetHighestService(0xc0002b5c80, 0x17, 0xc00003f0d0, 0x3, 0xc000040510, 0x2c, 0xc00003f0d8, 0x5, 0xc000048980, 0x1, ...)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/register/register.go:720 +0x3fb
github.com/open-horizon/anax/cli/register.AddAllRequiredSvcs(0xc0002b5c80, 0x17, 0xc00003f0d0, 0x3, 0xc000040510, 0x2c, 0xc00003f0d8, 0x5, 0x0, 0x0, ...)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/register/register.go:776 +0x4aa
github.com/open-horizon/anax/cli/register.AddAllRequiredSvcs(0xc0002b5c80, 0x17, 0xc00003ed96, 0x3, 0xc000040180, 0x2d, 0xc00003ed99, 0x5, 0xc00003eda0, 0x5, ...)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/register/register.go:783 +0x6b9
github.com/open-horizon/anax/cli/register.CreateInputFile(0x7ffed85ef685, 0x7, 0x7ffed85ef6a1, 0x4, 0x170451e, 0x5, 0x7ffed85ef675, 0xf, 0x7ffed85ef6a9, 0xc)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/register/register.go:819 +0xfe1
main.main()
	/tmp/anax-gopath/src/github.com/open-horizon/anax/cli/hzn.go:888 +0x14da6
````

**Comment by sirotsinskuy** [comment]
Working on it

**Comment by sirotsinskuy** [comment]
@linggao regarding the "prompt the user to add a property for privileged" part - does it mean to merely show the user the node policy properties you've provided (for enabling allowPrivileged), or we can ask if the user wants to save that as a file along with the userinput file?

**Comment by linggao** [comment]
Creating a node policy file is a good idea. Thanks for the suggestion. The file should look like this. You can use the same name as the user input file from -f flag and append `_np.json`. Anyway, let the user know that a sample node policy file is created.
````
{
  "properties": [
    {
      "name": "openhorizon.allowPrivileged",
      "value": true
    }
  ]
}
````
