### ISSUE TITLE
Panic in CSS code when HTTP request fails under heavy load

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2229]
Under heavy load, the CSS calls in to the exchange can fail and sometimes results in a panic that I found in the CSS logs

```
2020/12/14 13:44:42 http: panic serving 172.30.110.221:41198: runtime error: invalid memory address or nil pointer dereference
goroutine 427295470 [running]:
net/http.(*conn).serve.func1(0xc0009cab40)
        /usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x8cb1c0, 0xd24170)
        /usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/open-horizon/anax/css.(*HorizonAuthenticate).verifyNodeIdentity(0xc0000bc040, 0xc0005ff765, 0x1f, 0xc0005ff740, 0xf, 0xc0005ff785, 0xf, 0xc000022551, 0x1b, 0x0, ...)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/css/horizonAuthenticate.go:410 +0x36b
github.com/open-horizon/anax/css.(*HorizonAuthenticate).authenticateWithExchange(0xc0000bc040, 0xc0003c7b04, 0x0, 0xc0005ff740, 0x44, 0xc0005ff785, 0xf, 0xc000022551, 0x1b, 0x1db5440ce9eb5f, ...)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/css/horizonAuthenticate.go:158 +0x164
github.com/open-horizon/anax/css.(*HorizonAuthenticate).Authenticate(0xc0000bc040, 0xc0005f8f00, 0xd322a0, 0x44, 0xd5e5c0, 0x40c000, 0xc0003d3f40)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/css/horizonAuthenticate.go:120 +0x343
github.com/open-horizon/edge-sync-service/core/security.Authenticate(0xc0005f8f00, 0x1f, 0x9520a3, 0x1, 0x0, 0x2)
        /tmp/anax-gopath/pkg/mod/github.com/open-horizon/edge-sync-service@v0.10.12/core/security/security.go:135 +0x1b7
github.com/open-horizon/edge-sync-service/core/security.ValidateSPIRequestIdentity(0xc0005f8f00, 0x41468f, 0x7f2875d32f00, 0x20300000000000, 0x40c056, 0x400, 0x7f2875d33000, 0x20300000000000)
        /tmp/anax-gopath/pkg/mod/github.com/open-horizon/edge-sync-service@v0.10.12/core/security/security.go:311 +0xda
github.com/open-horizon/edge-sync-service/core/communications.(*HTTP).handleGetUpdates(0xc0000c60f0, 0xa24740, 0xc0005ec700, 0xc0005f8f00)
        /tmp/anax-gopath/pkg/mod/github.com/open-horizon/edge-sync-service@v0.10.12/core/communications/httpCommunication.go:160 +0x43
github.com/open-horizon/edge-sync-service/core/communications.(*HTTP).handleObjects(0xc0000c60f0, 0xa24740, 0xc0005ec700, 0xc0005f8f00)
        /tmp/anax-gopath/pkg/mod/github.com/open-horizon/edge-sync-service@v0.10.12/core/communications/httpCommunication.go:887 +0x22c
net/http.HandlerFunc.ServeHTTP(0xc000390610, 0xa24740, 0xc0005ec700, 0xc0005f8f00)
        /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.StripPrefix.func1(0xa24740, 0xc0005ec700, 0xc0005f8e00)
        /usr/local/go/src/net/http/server.go:2051 +0x18a
net/http.HandlerFunc.ServeHTTP(0xc0003cc4e0, 0xa24740, 0xc0005ec700, 0xc0005f8e00)
        /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xd321a0, 0xa24740, 0xc0005ec700, 0xc0005f8e00)
        /usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xd328c0, 0xa24740, 0xc0005ec700, 0xc0005f8e00)
        /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0009cab40, 0xa26240, 0xc001043ec0)
        /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c
```

In some cases, the HTTP invocation can fail and the resp must be null causing a problem for this line (line # 410)
```
	defer resp.Body.Close()
```

**Comment by dlarson04** [comment]
Thinking about this issue more... In times of heavy load on the exchange, an individual HTTP request could fail. The agbot/agent code accounts for this by implementing retry logic. See 

https://github.com/open-horizon/anax/blob/master/exchange/rpc.go#L916

Where this InvokeExchange function checks for a transport error and callers of this like

https://github.com/open-horizon/anax/blob/master/exchange/rpc.go#L1143

will retry if there is a transport error. (The number of retries is set by the type of exchange call made). I think the CSS code should implement retry logic in a similar manner.

**Comment by dlarson04** [comment]
Verified
