### ISSUE TITLE
Intermittent Agbot panic checking service version

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2309]
I am seeing an intermittent panic in the agbot code (2 times yesterday)
```
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot error panic: runtime error: index out of range [0] with length 0
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot goroutine 352 [running]:
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/semanticversion.singleVersion(0x0, 0x0, 0x1b30a1a)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/semanticversion/version.go:311 +0x112
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/semanticversion.Version_Expression_Factory(0x0, 0x0, 0x5, 0x1, 0x4)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/semanticversion/version.go:72 +0x25e
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/exchange.ServiceResolver(0xc00013a9a0, 0x12, 0xc00050c439, 0x3, 0xc00050c440, 0x5, 0xc001035ce6, 0x5, 0xc000604180, 0x194acc0, ...)
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot   /tmp/anax-gopath/src/github.com/open-horizon/anax/exchange/service.go:635 +0x96f
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/exchange.GetHTTPServiceResolverHandler.func1(0xc00013a9a0, 0x12, 0xc00050c439, 0x3, 0xc00050c440, 0x5, 0xc001035ce6, 0x5, 0x1e, 0xc00088da40, ...)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/exchange/handlers.go:
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot 177 +0xbb
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).InitiateNewAgreement(0xc0002053b0, 0x1e90cc0, 0xc00000c2a0, 0xc0000bdc00, 0xc0004a44b0, 0xc000135f20, 0x24)
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot   /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementworker.go:450 +0x700
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BasicAgreementWorker).start(0xc00058b140, 0xc00013e5a0, 0xc0004a44b0)
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot   /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_agreement_worker.go:152 +0x28ff
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot created by github.com/open-horizon/anax/agreementbot.(*BasicProtocolHandler).Initialize
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_protocol_handler.go:70 +0x2a9
```        
I saw this a couple of days ago and made a debug module were I print out the version… It should look like this

```
Feb 17 14:41:49 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot info I0217 19:41:49.225682       9 service.go:327] Exchange RPC doug:  calling Version_Expression_Factory with version [0.0.0,INFINITY)
Feb 17 14:41:49 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot info I0217 19:41:49.225694       9 version.go:71] Doug singleVersion with ver_string [0.0.0,INFINITY)
```
but this explains the panic in the message right before the panic
```
Feb 17 14:42:14 ibm-edge-agbot-b587f874f-bddrq ibm-edge-agbot info I0217 19:42:14.921316       9 version.go:71] Doug singleVersion with ver_string
```

Somehow this version string is getting nulled out before checking its value

Might only happen under high load so will add the perf label

**Comment by dabooz** [comment]
I am going to fix the panic with this issue, but there is another problem lurking. The stack trace doesnt show enough info to know why the version string was empty, which it should never be. With this fix, an error will be returned, so debug will proceed from there if/when the underlying problems occurs again.

**Comment by dlarson04** [comment]
Verified in amd64_agbot:2.28.0-298.202103020412.b159c916
