### ISSUE TITLE
Occasional panic in agbot when MMS objects are deleted

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2569]
I had seen some agbot restarts when I have been deleting some MMS objects and found a panic in the agbot code.

This is from agreementbot/object_manager.go#UpdatePolicies

I added some debug messages to try to understand what is happening. I haven't come up with a reliable way to 
reproduce it but I think it occurs when more than 1 MMS object is deleted.  The size of m.orgMap[org][service] is decreasing and the ix is increasing

```
        // If there are object policies that have been deleted, we wont know until we ask the MMS if the object still exists.
        // Loop through all the cached object policies checking to see if they still exist.
        diff := time.Now().Unix() - m.garbageCollection
        if diff >= m.config.AgreementBot.MMSGarbageCollectionInterval {
                m.garbageCollection = time.Now().Unix()
                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Starting object policy garbage collection")))
                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Length of range m.orgMap: %d", len(m.orgMap))))
                for org, serviceMap := range m.orgMap {
                        glog.V(3).Infof(mmsLogString(fmt.Sprintf("For org %v, length of serviceMap: %d", org, len(serviceMap))))
                        for service, peList := range serviceMap {
                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("For service %v, length of peList: %d", service, len(peList))))
                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Size of m.orgMap[org][service] is %d", len(m.orgMap[org][service]))))
                                for ix, pe := range peList {
                                        glog.V(3).Infof(mmsLogString(fmt.Sprintf("ix: %d, pe.Policy.ObjectID: %s", ix, pe.Policy.ObjectID)))
                                        if obj, err := objQueryHandler(pe.Policy.OrgID, pe.Policy.ObjectID, pe.Policy.ObjectType); err != nil {
                                                glog.Errorf(mmsLogString(fmt.Sprintf("error reading object %v %v %v, %v", pe.Policy.OrgID, pe.Policy.ObjectID, pe.Policy.ObjectType, err)))
                                        } else if obj == nil {
                                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("object %v/%v %v has been deleted", pe.Policy.OrgID, pe.Policy.ObjectID, pe.Policy.ObjectType)))
                                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Pre -> Size of m.orgMap[org][service] is %d", len(m.orgMap[org][service]))))
                                                m.orgMap[org][service] = append(m.orgMap[org][service][:ix], m.orgMap[org][service][ix+1:]...)
                                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Success slice subset of %d to %d", ix, (ix+1))))
                                                glog.V(3).Infof(mmsLogString(fmt.Sprintf("Post -> Size of m.orgMap[org][service] is %d", len(m.orgMap[org][service]))))
                                        }
                                }
                        }
                }
        }
```     

The next section that checks for 

```
// Find services in the cache that are not referenced by a given object id any more. This can happen if the service
// reference in the object policy is changed.
```

does the same type of slice append so I think there is a potential for a panic there too... 

I will add logs in a minute

The actual panic is 

```
I0611 13:23:09.549323       8 object_manager.go:208] MMS Object Policy Manager: Pre -> Size of m.orgMap[org][service] is 13
panic: runtime error: slice bounds out of range [14:13]
goroutine 6917 [running]:
github.com/open-horizon/anax/agreementbot.(*MMSObjectPolicyManager).UpdatePolicies(0xc000704660, 0xc000047440, 0xf, 0xc00064ff88, 0xc0004c6b80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/object_manager.go:209 +0x3a2c
github.com/open-horizon/anax/agreementbot.(*AgreementBotWorker).handleObjectPoliciesChange(0xc000492000, 0xc00088c3a0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementbot.go:1305 +0x18f
 +0x1250
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/agreementbot.go:576
created by github.com/open-horizon/anax/agreementbot.(*AgreementBotWorker).CommandHandler
```

**Comment by dlarson04** [comment]
[agbot-logs-issue-2569.zip](https://github.com/open-horizon/anax/files/6640023/agbot-logs-issue-2569.zip)

**Comment by dlarson04** [comment]
This issue has been verified... Closing
