### ISSUE TITLE
panic in agbot on basicagreementreplyupdate

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2744]
```
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot info I0811 22:56:37.801052       9 prioritized_workqueue.go:219] Prioritized Work Queue: queueing inbound high: WorkType: AGREEMENT_UPDATE_REPLY, Reply: {Type: basicagreementupdatereply, Protocol: Basic, Version: 1, AgreementId: 02f098162dc135957e5c093dfda17dad2365a4617fde31ad23fb110519915da9 basicagreementupdatesecret true}, MsgEndpoint: , SenderId: ieam-roks-scale/plasmas1.fyre.ibm.com_x_horizon0, SenderPubKey: set, MessageId: 25926096
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot info I0811 22:56:37.801050       9 worker.go:348] CommandDispatcher: AgBot command processor non-blocking for commands
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot info I0811 22:56:37.801109       9 basic_agreement_worker.go:238] BasicAgreementWorker (5b1839c5-e9df-414a-923c-caa45632dc9c): received work: WorkType: AGREEMENT_UPDATE_REPLY, Reply: {Type: basicagreementupdatereply, Protocol: Basic, Version: 1, AgreementId: 02f098162dc135957e5c093dfda17dad2365a4617fde31ad23fb110519915da9 basicagreementupdatesecret true}, MsgEndpoint: , SenderId: ieam-roks-scale/plasmas1.fyre.ibm.com_x_horizon0, SenderPubKey: set, MessageId: 25926096
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot error panic: runtime error: invalid memory address or nil pointer dereference
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot [signal SIGSEGV: segmentation violation code=0x1 addr=0x240 pc=0x15f0c5d]
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot goroutine 361 [running]:
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BasicAgreementWorker).start(0xc00072e280, 0xc00003a7e0, 0xc000337920)
	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_agreement_worker.go:401 +0x2bbd
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot created by github.com/open-horizon/anax/agreementbot.(*BasicProtocolHandler).Initialize
Aug 11 18:56:37 ibm-edge-agbot-748964c45f-g4mjr ibm-edge-agbot 	/tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_protocol_handler.go:72 +0x2d0 
```

I think the agreement is for the other agbot so the agreement object is nil.

**Comment by dlarson04** [comment]
verified in agbot 2.29.0-559.202108210411.40bb7c13
