### ISSUE TITLE
Bug: agent could panic if 2.29.0 agent upgrades to 2.30.0

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3644]
### Describe the bug.

If 2.29.0 agent is registered to a hub and the hub upgrades and then the agent upgrades, a panic could occur if the agent stays registered..

```
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: panic: assignment to entry in nil map
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: goroutine 14 [running]:
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/persistence.(*ExchangeDevice).SetCertVersion.func1({{0xc00041be10, 0x10}, {0xc0004be528, 0x13}, {0x0, 0x0}, {0xc00041be20, 0x10}, {0xc00041bdf8, 0x6}, ...})
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/persistence/device.go:214 +0x9a
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/persistence.updateExchangeDevice(0xc000060017?, 0xc0005f7500?, {0xc00041be10, 0x10}, 0x0, 0xc000129bd8?)
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/persistence/device.go:228 +0xd9
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/persistence.(*ExchangeDevice).SetCertVersion(0xc000060017?, 0x1e?, {0xc00041be10?, 0x0?}, {0xc0005f7519?, 0xc0005fc280?})
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/persistence/device.go:213 +0x95
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/exchangesync.NodeInitalSetup(0x24cdb80?, 0xc000033a40?, 0xc000728498)
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/exchangesync/node.go:84 +0x126
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/agreement.(*AgreementWorker).syncNode(0xc000033a40)
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/agreement.go:324 +0xc7
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/agreement.(*AgreementWorker).Initialize(0xc000033a40)
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/agreement/agreement.go:288 +0x235
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: github.com/open-horizon/anax/worker.(*BaseWorker).Start.func1()
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:341 +0x76
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: created by github.com/open-horizon/anax/worker.(*BaseWorker).Start
Feb  9 00:00:07 edge-fdo-feb01-1 anax[470350]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/worker/worker.go:335 +0x98
Feb  9 00:00:07 edge-fdo-feb01-1 systemd[1]: horizon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### Describe the steps to reproduce the behavior.

Register a 2.29.0 agent to a Hub running newer code
Without unregistering/reregistering agent, update the agent code to 2.30.0 version

If the cert or the config file has a version in it, a panic can occur

### Expected behavior.

no panics after an upgrade

### Operating Environment

linux

**Comment by dlarson04** [comment]
verified this is fixed in the 2.30.0-1146 build... closing
