### ISSUE TITLE
cli: errors when calling some commands before registration

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#427]
Ran `hzn show` commands before calling `hzn register`, got the following errors. Please make the errors more readable for user.
````
# hzn show keys
Error: bad HTTP code from GET http://localhost/publickey: 424

# hzn show node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c3fad]

goroutine 1 [running]:
github.com/open-horizon/anax/cli/show.(*NodeAndStatus).CopyNodeInto(0xc4200e5b88, 0xc420064780)
	/horizon-deb-packager/dist/horizon-2.12.0~ppa~ubuntu.xenial/anaxtmpgopath/src/github.com/open-horizon/anax/cli/show/show.go:47 +0xad
github.com/open-horizon/anax/cli/show.Node()
	/horizon-deb-packager/dist/horizon-2.12.0~ppa~ubuntu.xenial/anaxtmpgopath/src/github.com/open-horizon/anax/cli/show/show.go:66 +0xc4
main.main()
	/horizon-deb-packager/dist/horizon-2.12.0~ppa~ubuntu.xenial/anaxtmpgopath/src/github.com/open-horizon/anax/cli/hzn.go:55 +0x1835

# hzn show workloads
Error: bad HTTP code from GET http://localhost/workloadconfig: 424

# hzn show services
Error: bad HTTP code from GET http://localhost/service: 424
````

**Comment by bmpotter** [comment]
Dave is changing the anax api to allow `get /publickey` before `post /node`, so i won't handle 424 for `hzn show keys`.

**Comment by bmpotter** [comment]
https://github.com/open-horizon/anax/pull/431
